# ======================
# APPLICATION CONFIG
# ======================

spring.application.name=cinema-auth

# Server configuration
server.port=8081

# Exclude problematic Spring Cloud auto-configuration
spring.autoconfigure.exclude=org.springframework.cloud.autoconfigure.LifecycleMvcEndpointAutoConfiguration,org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration


# ======================
# DATABASE CONFIGURATION
# ======================

spring.datasource.url=jdbc:mysql://mysql:3306/demo_db
 spring.datasource.username=root
 spring.datasource.password=root
 spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ======================
# JPA CONFIGURATION
# ======================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ======================
# SECURITY (JWT)
# ======================

# Secret key used to sign JWT tokens
# jwt.secret=cinemaSecretKey123

jwt.secret=9f3c2b8a7d6e4f1c0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5d4e3f2a1b0c9d8e7f


# Token validity duration (24 hours in ms)
jwt.expiration=86400000

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Kafka Configuration
spring.kafka.enabled=false
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=auth-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

#spring.datasource.url=jdbc:h2:mem:testdb
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.hibernate.ddl-auto=update
# spring.h2.console.enabled=true